## **Linear Algebra**

In [4]:
import numpy as np

a = np.array([1, 2, 3, 4])

b = np.array([[1, 2], [3, 4]])

zero_matrix = np.zeros((3, 3))

one_matrix = np.ones((3, 3))

rand_matrix = np.random.rand(3, 3)

identity_matrix = np.eye(5,2)

print("Vector a:", a)
print("Matrix b:\n", b)
print("\nZero matrix:\n", zero_matrix) 
print("\nOne matrix:\n", one_matrix)
print("\nRandom matrix:\n", rand_matrix)
print("\nIdentity matrix:\n", identity_matrix)



Vector a: [1 2 3 4]
Matrix b:
 [[1 2]
 [3 4]]

Zero matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Random matrix:
 [[0.80375714 0.32715181 0.26622705]
 [0.69402894 0.21572957 0.81580523]
 [0.42840569 0.40984246 0.53711568]]

Identity matrix:
 [[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B
D = A - B

print("C:\n", C)
print("D:\n", D)

Y = np.array([[1, 2]])
X = np.array([3, 4])

E = Y * X #hadamard product
F = Y @ X #matmul

print("E:\n", E)
print("F:\n", F)

G = Y.dot(X) #dot product

print("G:\n", G)




C:
 [[ 6  8]
 [10 12]]
D:
 [[-4 -4]
 [-4 -4]]
E:
 [[3 8]]
F:
 [11]
G:
 [11]


In [12]:
# Tính định thức của ma trận A
det_A = np.linalg.det(A)
print("Định thức của ma trận A:\n", det_A)

# Tính ma trận nghịch đảo của A
inv_A = np.linalg.inv(A)
print("\nMa trận nghịch đảo của A:\n", inv_A)

# Tính hạng của ma trận A
rank_A = np.linalg.matrix_rank(A)
print("\nHạng của ma trận A:\n", rank_A)

# Giải hệ phương trình Ax = B
x = np.linalg.solve(A, B)
print("\nNghiệm của hệ phương trình Ax = B:\n", x)

# Tính giá trị riêng và vector riêng của A
eig_val, eig_vec = np.linalg.eig(A)
print("\nGiá trị riêng của A:\n", eig_val)
print("\nVector riêng của A:\n", eig_vec)

# Phân tích SVD của ma trận A
U, S, V = np.linalg.svd(A)
print("\nMa trận U trong SVD:\n", U)
print("\nMa trận S trong SVD:\n", S) 
print("\nMa trận V trong SVD:\n", V)


Định thức của ma trận A:
 -2.0000000000000004

Ma trận nghịch đảo của A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Hạng của ma trận A:
 2

Nghiệm của hệ phương trình Ax = B:
 [[-3. -4.]
 [ 4.  5.]]

Giá trị riêng của A:
 [-0.37228132  5.37228132]

Vector riêng của A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Ma trận U trong SVD:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

Ma trận S trong SVD:
 [5.4649857  0.36596619]

Ma trận V trong SVD:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
